name: summon_bell
description: A new Flutter project.
# 以下の行は、`flutter pub publish`を使用して誤ってpub.devにパッケージを公開することを防ぎます。これはプライベートパッケージに適しています。
publish_to: 'none' # pub.devに公開する場合はこの行を削除してください。

# 以下は、アプリケーションのバージョンとビルド番号を定義します。
# バージョン番号は3つの数字でドットで区切られ、1.2.43のようになります。
# それに続いて任意のビルド番号が+で区切られます。
# バージョンとビルド番号は、それぞれ--build-nameと--build-numberを指定することでflutter buildで上書き可能です。
# Androidでは、build-nameはversionNameとして使用され、build-numberはversionCodeとして使用されます。
# Androidのバージョン情報については、https://developer.android.com/studio/publish/versioning を参照してください。
# iOSでは、build-nameはCFBundleShortVersionStringとして使用され、build-numberはCFBundleVersionとして使用されます。
# iOSのバージョン情報については、https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html を参照してください。
# Windowsでは、build-nameは製品およびファイルバージョンの主要、副要、およびパッチ部分として使用され、build-numberはビルドサフィックスとして使用されます。
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# 依存関係は、パッケージが動作するために必要な他のパッケージを指定します。
# パッケージの依存関係を最新のバージョンに自動的にアップグレードするには、`flutter pub upgrade --major-versions`を実行してください。あるいは、
# 依存関係は、以下のバージョン番号をpub.devで利用可能な最新のバージョンに変更することで手動で更新できます。利用可能な最新のバージョンを確認するには、`flutter pub outdated`を実行してください。
dependencies: # あなたのアプリケーションに必要なパッケージをここに追加します。
  flutter:
    sdk: flutter

  # Cupertino Icons iOSスタイルのアイコンにCupertinoIconsクラスを使用します。
  cupertino_icons: ^1.0.2

  # flutter hooks フックを使用して状態を管理します。
  flutter_hooks: ^0.20.3
  # hooks riverpod 状態を管理します。
  hooks_riverpod: ^2.4.9

  # @riverpod アノテーションを使用するために必要
  riverpod_annotation: ^2.3.3
  # flutter_chat_ui チャットUIを使用します。
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  # uuid ユニークなIDを生成します。
  uuid: ^4.2.1

  # drift sqlite orm
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  sqlite3: ^2.1.0



dev_dependencies: 
  # 開発に必要なパッケージをここに追加します。
  flutter_test:
    sdk: flutter

  # "flutter_lints"パッケージには、良いコーディング慣習を奨励するための推奨されるリントのセットが含まれています。
  # このパッケージは、あなたのパッケージのルートにある`analysis_options.yaml`ファイルで有効になります。
  # 特定のリントルールを無効にしたり、追加のルールを有効にする方法については、そのファイルを参照してください。
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.7

  # ビルドプロセスを管理するために必要なパッケージ
  # build_runner: ビルドを実行するためのツール
  build_runner: ^2.4.7

  # riverpod_generator: Riverpodライブラリのためのコードジェネレーター。データクラスやプロバイダの生成に使用されます。
  riverpod_generator: ^2.3.9

  drift_dev: ^2.14.0

# このファイルの一般的なDart部分に関する情報については、以下のページを参照してください：https://dart.dev/tools/pub/pubspec

# 以下のセクションはFlutterパッケージに特有のものです。
flutter:

  # 以下の行は、Material Iconsフォントがアプリケーションに含まれるようにするためのものです。
  # これにより、material Iconsクラスのアイコンを使用できるようになります。
  uses-material-design: true

  # アプリケーションにアセットを追加するには、以下のようにassetsセクションを追加します。
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
  # 画像アセットは、解像度に応じた複数の「バリアント」を指定することができます。詳細はこちら:
  # https://flutter.dev/assets-and-images/#resolution-aware

  # パッケージ依存関係からアセットを追加する詳細については、以下のリンクを参照してください。
  # https://flutter.dev/assets-and-images/#from-packages

  # アプリケーションにカスタムフォントを追加するには、ここである"flutter"セクションにfontsセクションを追加します。
  # このリストの各エントリーには、フォントファミリー名を示す"family"キーと、
  # フォントのアセットとその他の記述子を示す"fonts"キーのリストが必要です。例えば:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # パッケージ依存関係からフォントを追加する詳細については、以下のリンクを参照してください。
  # https://flutter.dev/custom-fonts/#from-packages
